### ISSUE TITLE
Updating sentry version to latest

### ISSUE THREAD

**Issue by emilsivervik** [timfish/sentry-rust-minidump#8]
Hello,

I'm wondering if you have any plans to update to latest version of sentry (`0.29.1`) any time soon? I've prepared 2 pull requests to this and https://github.com/timfish/sentry-test-server if you want some help.

**Comment by timfish** [comment]
Yes, feel free to submit PR's and I'll get them merged and released!

**Comment by emilsivervik** [comment]
Fantastic! It seems like I can't do PR's since I don't have permissions to this repository so what would be preferred flow?

**Comment by timfish** [comment]
You should be able to:
- Fork this repository
- Create a branch on your fork with the changes
- Submit a PR to this repo from your fork

**Comment by timfish** [comment]
Since I've not setup publish from CI, it was a lot less total work for me to make the changes just before publishing!

I've just published 0.4.1 which uses `sentry@0.29`.

**Comment by emilsivervik** [comment]
Got it, thanks
